/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import type { DayJsLocale } from '@/lib/dayjs/Locales.ts';
import { DAYJS_LOCALES } from '@/lib/dayjs/Locales.ts';
import { DEFAULT_LANGUAGE } from '@/lib/ISOLanguageUtil.ts';

export const getDayJsLocale = (locale: string): DayJsLocale => {
    if (DAYJS_LOCALES.includes(locale as DayJsLocale)) {
        return locale as DayJsLocale;
    }

    if (DAYJS_LOCALES.includes(locale.toLowerCase() as DayJsLocale)) {
        return locale.toLowerCase() as DayJsLocale;
    }

    const convertedLocale = locale.split('-')[0].toLowerCase();
    if (DAYJS_LOCALES.includes(convertedLocale as DayJsLocale)) {
        return convertedLocale as DayJsLocale;
    }

    return DEFAULT_LANGUAGE;
};

export const importDayJsLocale = async (locale: string): Promise<DayJsLocale> => {
    const dayjsLocale = getDayJsLocale(locale);

    try {
        // oxlint-disable-next-line no-use-before-define
        await localesToImport[dayjsLocale]();
    } catch (e) {
        // ignore - dayjs falls back to "en" by default
    }

    return dayjsLocale;
};

/**
 * **IMPORTANT:**
 *
 * This is generated by the `dayjs:gen-locales-imports` script
 */
const localesToImport: Record<(typeof DAYJS_LOCALES)[number], () => Promise<unknown>> = {
    en: () => import('dayjs/locale/en.js'),
    es: () => import('dayjs/locale/es.js'),
};
