export type DayJsLocale = (typeof DAYJS_LOCALES)[number];

/**
 * **IMPORTANT:**
 *
 * This is generated by the `dayjs:gen-locales-array` script
 */
export const DAYJS_LOCALES = ['en', 'es'] as const;
